name: CI

on:
  workflow_dispatch:

jobs:
  Build_x64:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: rainbow
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ionescu007/VisualUefi
          submodules: true
          path: VisualUefi

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Set up NASM
        uses: ilammy/setup-nasm@v1.5.1

      - name: Build
        run: |
          cd VisualUefi\EDK-II
          msbuild /t:build EDK-II.sln /p:Configuration="Release" /p:Platform=x64 -maxcpucount:8
      - name: Build
        run: |
          msbuild /t:build rainbow\rainbow\rainbow.sln /p:Configuration="Release" /p:Platform=x64 -maxcpucount:8

      - uses: actions/upload-artifact@v4
        with:
          name: rainbow_x64
          path: |
            rainbow
