name: CI

on:
  workflow_dispatch:
  push:

jobs:
  Build_x64:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2
        
      - name: Set up NASM
        uses: ilammy/setup-nasm@v1.5.1

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Build
        run: |
          cd EDK-II
          msbuild /t:build EDK-II.sln /p:Platform=x64 -maxcpucount:8

      - name: Build
        run: |
          cd rainbow
          msbuild /t:build rainbow.sln /p:Platform=x64 -maxcpucount:8

      - uses: actions/upload-artifact@v4
        with:
          name: rainbow_x64
          path: |
            rainbow
